### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions.

### ISSUE THREAD

**Issue by Gshaoo** [boathit/t2vec#33]
Hello, boathit, I am a beginner in trajectory mining. When I was training, I encountered a problem that could not be solved. I hope to get your answer. The problem is ：
Traceback (most recent call last):
  File "t2vec.py", line 121, in <module>
    train(args)
  File "/home/ubuntu/gsh/t2vec-master/train.py", line 177, in train
    trainData.load(args.max_num_line)
  File "/home/ubuntu/gsh/t2vec-master/data_utils.py", line 155, in load
    self.srcdata = list(map(np.array, self.srcdata))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5453003,) + inhomogeneous part.

**Comment by Jyl595** [comment]
Hello Gshaoo, I also encountered the same problem, did you solve the problem?

**Comment by liuwj2000** [comment]
Hi, I solve it when I use numpy 1.23

**Comment by csjiezhao** [comment]
you can solve this problem by:
`self.srcdata = list(map(np.array, self.srcdata))` --> `self.srcdata = [np.array(e, dtype=object) for e in self.srcdata]`
